language: node_js

node_js:
  - 10
  - 8

notifications:
  email: false

before_deploy:
  - npm run build
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  local-dir: "build"
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    node: 10
